parameters:
    algolia.indexer.class: Algolia\AlgoliaSearchBundle\Indexer\Indexer
    algolia.connection_timeout: ~
    algolia.indexer_subscriber.orm.class: Algolia\AlgoliaSearchBundle\EventListener\AlgoliaSearchDoctrineORMEventSubscriber
    algolia.indexer_subscriber.mongodb_odm.class: Algolia\AlgoliaSearchBundle\EventListener\AlgoliaSearchDoctrineMongoDBODMEventSubscriber

services:
    algolia.client:
        class: AlgoliaSearch\Client
        arguments:
            - "%algolia.application_id%"
            - "%algolia.api_key%"

    algolia.debug_client:
        class: Algolia\AlgoliaSearchBundle\Debug\DebugClient
        arguments:
            - "%algolia.application_id%"
            - "%algolia.api_key%"
        calls:
            - [disableRequests, ["%algolia.disable_requests%"]]
            - [setStopwatch, ["@debug.stopwatch"]]

    algolia.client_data_collector:
        class: Algolia\AlgoliaSearchBundle\DataCollector\ClientDataCollector
        public: false
        arguments:
            - "@algolia.client"
        tags:
            - {name: data_collector, template: "@AlgoliaAlgoliaSearch/Collector/algolia.html.twig", id: "algolia.client_data_collector"}

    algolia.indexer:
        class: "%algolia.indexer.class%"
        calls:
            - [setEnvironment, ["%kernel.environment%"]]
            - [setIndexNamePrefix, ["%algolia.index_name_prefix%"]]
            - [setApiSettings, ["%algolia.application_id%", "%algolia.api_key%", "%algolia.connection_timeout%"]]
            - [setClient, ["@algolia.client"]]

    algolia.indexer_subscriber.abstract:
        abstract: true
        arguments:
            - "@algolia.indexer"
            - "%algolia.catch_log_exceptions%"
            - "@?logger"

    algolia.indexer_subscriber.orm:
        parent: algolia.indexer_subscriber.abstract
        class: "%algolia.indexer_subscriber.orm.class%"
        tags:
            - {name: doctrine.event_subscriber}

    algolia.indexer_subscriber.mongodb_odm:
        parent: algolia.indexer_subscriber.abstract
        class: "%algolia.indexer_subscriber.mongodb_odm.class%"
        tags:
            - {name: doctrine_mongodb.odm.event_subscriber}
