language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot

matrix:
    allow_failures:
        - php: 7.4snapshot

branches:
    only:
        - master
        - 2.x

jobs:
    include:
        - stage: phpstan
          php: 7.2
          script: composer test:install && composer test:style

install:
    - wget https://alg.li/algolia-keys && chmod +x algolia-keys
    - composer install

script:
    - eval $(./algolia-keys export) && ./vendor/bin/phpunit -v
