language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - nightly

matrix:
    allow_failures:
        - php: nightly

branches:
    only:
        - master
        - 2.x

jobs:
    include:
        - stage: phpstan
          php: 7.2
          before_install: composer require --no-update phpstan/phpstan "^0.10.6"
          script: vendor/bin/phpstan analyse

install:
    - wget https://alg.li/algolia-keys && chmod +x algolia-keys
    - composer install

script:
    - eval $(./algolia-keys export) && ./vendor/bin/phpunit -v
