language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

branches:
    only:
        - master
        - 2.x

before_script:
    - wget https://alg.li/algolia-keys && chmod +x algolia-keys
    - composer install

script:
    - ./vendor/bin/phpstan analyse src --level=1
    - eval $(./algolia-keys export) && ./vendor/bin/simple-phpunit -v
